### ISSUE TITLE
Unable to run it on the local machine.

### ISSUE THREAD

**Issue by GauravKanted** [Khan/graphie-to-png#13]
Hi, @mpolyak  we are unable to run this project on our local. Please find the error screenshots below and let us know where we are going wrong. Have modified the secrets.py file and tested the S3 Bucket for all relevant access.
![Screenshot from 2020-02-19 11-31-05](https://user-images.githubusercontent.com/22241993/74808275-812ccb00-5310-11ea-8cf9-cbd9d8eaf7bc.png)
![Screenshot from 2020-02-19 11-30-41](https://user-images.githubusercontent.com/22241993/74808281-825df800-5310-11ea-9d3d-fe0c34929121.png)
![Screenshot from 2020-02-19 11-48-45](https://user-images.githubusercontent.com/22241993/74808283-82f68e80-5310-11ea-8467-69ce7e24997d.png)

**Comment by GauravKanted** [comment]
Update, we fixed the third_party modules and got it to run. But the rendering takes too long and the server returns Internal Server Error.

![Screenshot from 2020-02-19 14-35-27](https://user-images.githubusercontent.com/22241993/74818763-3ec1b900-5325-11ea-8211-b91053f7b64b.png)

**Comment by danielhollas** [comment]
I could never make it work either. @GauravKanted can you describe what did you do to fix third_party modules?

**Comment by GauravKanted** [comment]
@danielhollas Hey, so first we figured that after you clone the repo, most third-party folders are empty. So we went around manually cloning each of the 3 third-party repos and then unzipping them to the respective folders. 

P.s Make sure to run npm install in the root directory to have your node_modules.

**Comment by mpolyak** [comment]
Running `git submodule update --init --recursive` should also pull third_party repos.

**Comment by GauravKanted** [comment]
@mpolyak Thanks, got it working.
